update latest API for guest configuration
projectkudu/ARMExplorer pull request #324
Opened 2021-09-07 17:32 UTC by mgreenegit

It appears that the "definitions" file is no longer needed? Confirm?

2021-09-07 17:48 UTC, balag0 commented
If there is a json file that references an item from the definitions file, then the definitions file will be needed.
Does having the definitions file cause any issues or you are just doing some cleanup?

2021-09-07 17:50 UTC, mgreenegit commented
just cleanup. what is the best way to tell if it is needed?

2021-09-08 03:02 UTC, balag0 commented
Easiest way is to run a local copy of this app. On launching the app, all the swaggers will be parsed and there will be a filenotfoundexception or definitionnotfound  exception for any missing but referenced files.

Instructions might be a little outdated but you should be able to get the general idea.
https://github.com/projectkudu/AzureResourceExplorer#instructions

Other option is to walk through different files and see if they have references to other files.

2021-09-08 20:20 UTC, mgreenegit commented
confirmed it is needed. restored the file.

2021-09-11 05:11 UTC, balag0 requested changes

2021-09-11 05:11 UTC, balag0 commented on App_Data/SwaggerSpecs/Microsoft.GuestConfiguration/guestconfiguration.json
> +            "$ref": "../../common/v1/definitions.json#/parameters/SubscriptionIdParameter"
common types are available at a different relative path (you can see where the old file was referencing parameters/SubscriptionIdParameter from as an example)

2021-09-11 05:11 UTC, balag0 commented on App_Data/SwaggerSpecs/Microsoft.GuestConfiguration/guestconfiguration.json
> +            "$ref": "../../common/v1/definitions.json#/parameters/VmNameParameter"
if this type is not available in the common-types file, then we would need a local copy of this file in this folder and update the path to reference from that newly added file.

2026-04-21 20:28 UTC, closed without merging